volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true

services:
  postgres:
    image: postgres:14.5-bullseye
    environment:
      - POSTGRES_DB=jeoparty
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: postgresql://user:password@postgres/jeoparty
      WAIT_HOSTS: postgres:5432
      SIGNING_KEY: 87fe4a3fcfb60092dbaeb854a196bc3d9b190aed7930c734749e85245de698420c25f8e6899c421b4494e99459e01058de5daa9d49584cd62ec975da9aea33dc
  frontend:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - 3000:3000
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: http://localhost:8000
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
      # needs to be 8082:80 and need to specify the listening address
    environment:
      PGADMIN_DEFAULT_EMAIL: juiceman2009@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: 1
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
