volumes:
  postgres-data:
    external: true

services:
  postgres:
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    environment:
      POSTGRES_DATABASE: jeoparty
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  fastapi:
    environment:
      DATABASE_URL: postgresql://user:password@postgres/jeoparty

  frontend:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
